### ISSUE TITLE
risc0 depends on protobuf-src which fails to compile in docker

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1074]

**Comment by GopherJ** [comment]
```
25.31   checking how to run the C++ preprocessor... /lib/cpp
25.31
25.31   --- stderr
25.31   configure: error: in `/parallel/target/release/build/protobuf-src-1220dcc56cdfb231/out/install/build':
25.31   configure: error: C++ preprocessor "/lib/cpp" fails sanity check
25.31   See `config.log' for more details
25.31   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/autotools-0.2.6/src/lib.rs:781:5:
25.31
25.31   command did not execute successfully, got: exit status: 1
25.31
25.31   build script failed, must exit now
25.31   stack backtrace:
25.31      0: rust_begin_unwind
25.31                at /rustc/97c81e1b537088f1881c8894ee8579812ed9b6d1/library/std/src/panicking.rs:597:5
25.31      1: core::panicking::panic_fmt
25.31                at /rustc/97c81e1b537088f1881c8894ee8579812ed9b6d1/library/core/src/panicking.rs:72:14
25.31      2: autotools::fail
25.31      3: autotools::Config::build
25.31      4: build_script_build::main
25.31      5: core::ops::function::FnOnce::call_once
25.31   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
25.31 warning: build failed, waiting for other jobs to finish...

```

**Comment by GopherJ** [comment]
build stage:

```
FROM docker.io/paritytech/ci-linux:production as builder
LABEL description="This is the build stage. Here we create the binary."

RUN apt update -y && apt install -y protobuf-compiler g++

ARG PROFILE=release

WORKDIR /parax

COPY . /parax

RUN cargo install cargo-risczero

RUN cargo build --profile $PROFILE
```

**Comment by GopherJ** [comment]
If I install libprotobuf-dev as well it gives another different error, generally seems tricky to compile protobuf-src. This issue may not be related to risc0 but just trying to find a way to package the binary into docker

**Comment by flaub** [comment]
`protoc` (the protobuf compiler) is built from source, so installing `protobuf-compiler` won't help in this case AFAIK.

From the error message above it looks like a C++ toolchain isn't installed properly (specifically cpp, the c++ pre-processor, doesn't seem to be installed).

**Comment by flaub** [comment]
If you use `cargo binstall cargo-risczero` it should avoid needing to build `cargo-risczero` from source, which may avoid the whole issue.

**Comment by GopherJ** [comment]
wierd I'm still having the following:

```
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it)
```

do you have an example docker that we can use ?

**Comment by flaub** [comment]
This was added recently: https://github.com/risc0/risc0/blob/main/.github/containers/release/Dockerfile
