### ISSUE TITLE
[BUG] Context leak when proving with Metal

### ISSUE THREAD

**Issue by Cardosaum** [risc0/risc0#1264]
## Bug Report
When running the [`loop` example](https://github.com/risc0/risc0/blob/e6e45e7922ca1e8fd94f20f5eb37c237b0dada0f/risc0/zkvm/examples/loop.rs), a warning is reported for proofs larger than 1k cycles, with the message `Context leak detected, msgtracer returned -1`. 

The proving seems to work for proofs of up to 4.9k cycles, but after that it fails with a panic in `/risc0/zkp/src/prove/prover.rs:126:36`

## Steps to Reproduce
The original bug was found in branch `cardosaum/loop-example-better-stats`, when executing the example with the `--join` flag enabled (which instructs the zkVM to execute, prove, lift and join - Essentially producing a single proof as result of proving each segment individually).

1. Checkout a known version where the bug is present: `git checkout e6e45e792`
1. Change current directory to `zkvm` folder: `cd ./risc0/zkvm/`
2. Compile and run the `loop` example with a lower `po2` with the `metal` feature enabled and instructing the proving to perform lifts and joins: `cargo run --release --example loop -F prove -F metal -- --po2 15 --join`

The result I'm getting is as follows:

```
cargo r -r --example loop -F prove -F metal -- -p 15 --join

Running `<path>/risc0/target/release/examples/loop -p 15 --join`
| Executor Cycles |   Prover Cycles |        Segments |        Duration |             RAM |            Seal |           Speed |
|             432 |               2 |              14 |          1:24.6 |         962.6MB |           2.8MB |          5.2khz |
|             528 |              38 |              17 |          1:42.7 |         962.6MB |           3.5MB |          5.3khz |
|             784 |             146 |              25 |          2:16.2 |         962.6MB |           5.1MB |          5.9khz |
|            1.1k |             290 |              36 |            3:07 |         962.6MB |           7.3MB |          6.2khz |
Context leak detected, msgtracer returned -1
|            1.9k |             578 |              59 |          5:08.7 |         962.6MB |            12MB |          6.2khz |
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
|            4.9k |            1.8k |             154 |         13:30.1 |         962.6MB |          31.3MB |          6.2khz |
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
Context leak detected, msgtracer returned -1
thread 'main' panicked at <path>/risc0/zkp/src/prove/prover.rs:126:36:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at risc0/zkvm/examples/loop.rs:232:5:
assertion failed: ok
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Expected behavior
The proving should be carried over without any context leak nor panics, only reporting the values.

## Your Environment
- risc0-zkvm version: 
  - As defined in `Cargo.toml`: `0.21.0-alpha.1`
- `cargo risczero --version`: cargo-risczero 0.20.0-alpha.1
- Rust version: `rustc 1.73.0 (cc66ad468 2023-10-03)`
- Platform/OS: MacOS M2 Max, 32 GB, macOS Sonoma 14.2.1 (23C71)

## Additional context
It's important to hightlight that the `risc0-zkvm` version and the `cargo risczero` version differ, I'll report the result of running the same code with both versions being the same in a following comment.

**Comment by flaub** [comment]
My reading of this is that the context leak is just warning, and the panic is a separate issue. I think we should have two tickets.

**Comment by flaub** [comment]
The version differences won't matter if you use `-F metal` because that depends on `-F prove`, which embeds the prover into the binary (so it won't use the server).

**Comment by Cardosaum** [comment]
Thanks for additional context! 
Would there be anything else that I could report in order to add useful information?

**Comment by flaub** [comment]
It would be best if we could isolate the symptoms to a single execution, the smaller the reproduction case the better.
