### ISSUE TITLE
Can't prove using Cuda on my machine

### ISSUE THREAD

**Issue by dajuguan** [risc0/risc0#1284]
## Bug Report
Can't prove using Cuda.
```
thread 'main' panicked at /home/po/grant/paul/EthStorage-Grant/risc0/risc0/zkp/src/hal/cuda.rs:347:63:
called `Result::unwrap()` on an `Err` value: UnknownError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
## Steps to Reproduce
```
cargo install cargo-binstall
cargo binstall cargo-risczero
cargo risczero install
git clone -b v0.19.1 https://github.com/risc0/risc0.git`
cd risc0/examples/hello-world
cargo run --release  --  --method execute #ok
cargo run --release  --  --method prove #ok
cargo run --release -F cuda -- --method prove # throw error
```

## Expected behavior
`Prove is ok.`

## Your Environment
- risc0-zkvm version: v0.19.1
- Rust version: 1.75.0
- Platform/OS: `Linux qizhou-Lambda-Vector 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
- Cuda:

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:41:00.0  On |                  Off |
|  0%   38C    P8              24W / 480W |    114MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off | 00000000:61:00.0 Off |                  Off |
|  0%   31C    P8              28W / 480W |     13MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
```

**Comment by weikengchen** [comment]
I am doubting whether it is due to `cust` not supporting anything above cuda 12.0

**Comment by dajuguan** [comment]
Possibly, the issue could be due to the larger version of Linux, which may not be supported by certain libraries. I have observed that on a different machine running `Linux q7950 5.15.0-91-generic #101~20.04.1-Ubuntu` and equipped with the same CUDA driver, the prover actually works.

**Comment by weikengchen** [comment]
I am getting CUDA error "operating system" (a seemingly very rare CUDA error) consistently when I used cuda 12.3. I will test further with my AWS spot machines...

**Comment by dajuguan** [comment]
> I am getting CUDA error "operating system" (a seemingly very rare CUDA error) consistently when I used cuda 12.3. I will test further with my AWS spot machines...

Yeah, the issue seems not related to CUDA vesion but OS version. It works well with a lower version of Linux.

**Comment by intoverflow** [comment]
Same issue when running on Windows/wsl2:

```console
~/risc0/risc0/examples/hello-world$ cargo run --release -F cuda
   Compiling hello-world v0.1.0 (/home/tcarstens/risc0/risc0/examples/hello-world)
    Finished release [optimized + debuginfo] target(s) in 4m 47s
     Running `/home/tcarstens/risc0/risc0/examples/target/release/hello-world`
thread 'main' panicked at /home/tcarstens/risc0/risc0/risc0/zkp/src/hal/cuda.rs:433:63:
called `Result::unwrap()` on an `Err` value: UnknownError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

System info:
```console
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
$ wslfetch

               .-/+oossssoo+/-.               Windows Subsystem for Linux (WSL2)
           `:+ssssssssssssssssss+:`           tcarstens@DESKTOP-NS5KK71
         -+ssssssssssssssssssyyssss+-         Build: 22631
       .ossssssssssssssssssdMMMNysssso.       Branch: ni_release
      /ssssssssssshdmmNNmmyNMMMMhssssss/      Release: Ubuntu 22.04.3 LTS
     +ssssssssshmydMMMMMMMNddddyssssssss+     Kernel: Linux 5.15.133.1-microsoft-standard-WSL2
    /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Uptime: 0d 6h 29m
   .ssssssssdMMMNhsssssssssshNMMMdssssssss.
   +sssshhhyNMMNyssssssssssssyNMMMysssssss+
   ossyNMMMNyMMhsssssssssssssshmmmhssssssso
   ossyNMMMNyMMhsssssssssssssshmmmhssssssso
   +sssshhhyNMMNyssssssssssssyNMMMysssssss+
   .ssssssssdMMMNhsssssssssshNMMMdssssssss.
    /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
     +sssssssssdmydMMMMMMMMddddyssssssss+
      /ssssssssssshdmNNNNmyNMMMMhssssss/
       .ossssssssssssssssssdMMMNysssso.
         -+sssssssssssssssssyyyssss+-
           `:+ssssssssssssssssss+:`
               .-/+oossssoo+/-.
```
