### ISSUE TITLE
[BUG] Do not import `risc0-zkvm-platform/rust-runtime` for the host

### ISSUE THREAD

**Issue by weikengchen** [risc0/risc0#1329]
## Bug Report

We are looking to see if one can deploy RISC Zero prover as a [Ray remote function](https://docs.ray.io/en/latest/ray-core/tips-for-first-time.html) so that one can run distributed proof generation directly over io.net.

All it takes is to add a Python interface for RISC Zero prover, through https://github.com/PyO3/pyo3, by compiling RISC Zero into a Python module. An obstacle is that, when, in Python, we want to load this module, the system would complain that:

```
>>> import l2_r0prover
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cusgadmin/.pyenv/versions/pyo3/lib/python3.11/site-packages/l2_r0prover/__init__.py", line 1, in <module>
    from .l2_r0prover import *
ImportError: dlopen(/Users/cusgadmin/.pyenv/versions/pyo3/lib/python3.11/site-packages/l2_r0prover/l2_r0prover.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__end'
```

People who are familiar with RISC Zero can immediately think about what this `__end` is. It is from the allocator.
```rust
#[cfg(feature = "export-syscalls")]
#[no_mangle]
pub unsafe extern "C" fn sys_alloc_aligned(bytes: usize, align: usize) -> *mut u8 {
    extern "C" {
        // This symbol is defined by the loader and marks the end
        // of all elf sections, so this is where we start our
        // heap.
        //
        // This is generated automatically by the linker; see
        // https://lld.llvm.org/ELF/linker_script.html#sections-command
        static _end: u8;
    }
    ......
}
```
https://github.com/risc0/risc0/blob/main/risc0/zkvm/platform/src/syscall.rs#L657

The problem is that `__end` is not always available, and additionally, it is not really necessary for the host. Today, however, `Cargo.toml` of zkvm always import risc0-zkvm-platform and has rust-runtime feature on.
```toml
risc0-zkvm-platform = { workspace = true, features = [
  "rust-runtime",
  "export-getrandom",
] }
```
https://github.com/risc0/risc0/blob/main/risc0/zkvm/Cargo.toml#L35C1-L47C4

## Solution

It seems necessary to make sure that `rust-runtime` and `export-getrandom` are only used when it is in zkvm. 

A proposed change is to replace the toml entry above to:
```toml
risc0-zkvm-platform = { workspace = true, default-features = false }
```

And we additionally activate the features for zkvm target.
```toml
[target.'cfg(target_os = "zkvm")'.dependencies]
risc0-zkvm-platform = { workspace = true, features = [
  "rust-runtime",
  "export-getrandom",
] }
```

## Your Environment
- risc0-zkvm version: 0.19.1
- Rust version: 1.75.0
- Platform/OS: macOS 14.3 Beta

**Comment by weikengchen** [comment]
For more detail, the Python module is here compiled with crate type "cdylib", and it is being wrapped into a Python module by https://github.com/PyO3/maturin

**Comment by weikengchen** [comment]
I made a fork https://github.com/risc0/risc0/compare/main...l2iterative:risc0:no-rust-runtime-for-host?expand=1
currently used for this https://github.com/l2iterative/r0prover-python/tree/main, will update more detail.

**Comment by flaub** [comment]
The long-term way I'd like to introduce language bindings (including python) is to use the client/server interface, so that we don't need to worry about issues like this (dynamic linking and generally trying to get multiple libraries into a single process can be challenging in really weird and hard to diagnose/fix ways).

**Comment by weikengchen** [comment]
But today to call r0vm one still needs to import the entire zkvm right? It is actually just calling the r0vm

**Comment by flaub** [comment]
The intent is for protobuf to be used as the protocol between client/server. So the idea would be for us to run `protoc` to generate python code. Then there's a bit of glue code to spin up the server.

**Comment by weikengchen** [comment]
I am currently in favor of this approach since I just couldn't get Ray to work after a week of attempt.

1. Python bindings. It can be a separate Python module that wraps the api client to the external prover.

2. External prover aka r0vm, we can just copy-paste the compiled executable file into the Python wheel.

3. Find a way to keep the handle of the external prover, so we do not need to open and close every time we perform an operation.

**Comment by weikengchen** [comment]
The deep reason is that being in the same process (or children) without explicitly spawning a new one is just hard to work with CUDA. 

If one uses CUDA for some tasks and then invokes RISC Zero-enabled CUDA, chances are that parents have already initialized the CUDA and there are no ways to revert it.

-----

It would be ideal though, if r0vm can be compiled with CUDA support (discussed by a separate PR) and if we can tell sppark and R0 which GPU to use, which is a feature currently missing in some ways (though, one can hack it by giving an environment variable, CUDA_VISIBLE_DEVICES, and this might be the best solution).
