### ISSUE TITLE
risc0-main/examples/smartcore-ml/src Fails

### ISSUE THREAD

**Issue by saileshp56** [risc0/risc0#1352]
## Bug Report
I am getting an error when trying to run main.rs right out of the box

## Steps to Reproduce
1. Clone repo
2. Navigate to risc0-main/examples/smartcore-ml/src
3. run ```cargo test``` 

## Expected behavior
Not an error

## Your Environment
- risc0-zkvm version: up to date on main branch
- Rust version: stable-aarch64-apple-darwin unchanged - rustc 1.75.0 (2023-12-21)
- Platform/OS: M1 Mac OS

**Comment by flaub** [comment]
What is the error that you're seeing? Please report as much context as you can so that we can identify and eventually fix the issue.

**Comment by saileshp56** [comment]
I apologize I forgot to include the error:
```
running 2 tests
thread 'main' panicked at risc0/r0vm/src/lib.rs:176:18:
called `Result::unwrap()` on an `Err` value: incompatible client version: 0.21.0-alpha.1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test::svc ... FAILED
thread 'main' panicked at risc0/r0vm/src/lib.rs:176:18:
called `Result::unwrap()` on an `Err` value: incompatible client version: 0.21.0-alpha.1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test::basic ... FAILED

failures:

---- test::svc stdout ----
thread 'test::svc' panicked at smartcore-ml/src/main.rs:157:58:
called `Result::unwrap()` on an `Err` value: failed to fill whole buffer
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::basic stdout ----
thread 'test::basic' panicked at smartcore-ml/src/main.rs:69:54:
called `Result::unwrap()` on an `Err` value: failed to fill whole buffer


failures:
    test::basic
    test::svc

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.05s

```

**Comment by weikengchen** [comment]
The issue is about incompatible client version: 0.21.0-alpha.1.

Here is the solution:

- git clone this repo, which I think you have already done.
- `cargo install --path risc0/cargo-risczero` which would update the system's `cargo-risczero` and `r0vm` to 0.21.0-alpha.1.

**Comment by flaub** [comment]
While it is possible to build from source, note that it can take a very long time to do so. We recommend using releases and to that end there is a branch for each release that the examples are designed to work with. Here's some more information about this: https://dev.risczero.com/api/next/zkvm/examples

**Comment by saileshp56** [comment]
> The issue is about incompatible client version: 0.21.0-alpha.1. Basically, the `host` calls `r0vm` to generate the proof, but `r0vm` (which is from the previous installation, and would be older) finds that the version mismatches, and refuses to proceed.
> 
> Here is the solution:
> 
> * git clone this repo, which I think you have already done.
> * `cargo install --path risc0/cargo-risczero` which would update the system's `cargo-risczero` and `r0vm` to 0.21.0-alpha.1.

I had to change the command you told me to run because it was giving me errors about the path not having a Cargo.toml file:
```/risc0-main/examples/smartcore-ml/risc0/cargo-risczero` is not a directory. --path must point to a directory containing a Cargo.toml file.```

I tried the command:
```cargo install --path .```
 in risc0-main/examples/smartcore-ml
Then I ran ```cargo test``` in the same file

I got the following error:
```
running 2 tests
thread 'main' panicked at risc0/r0vm/src/lib.rs:176:18:
called `Result::unwrap()` on an `Err` value: incompatible client version: 0.21.0-alpha.1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test::svc ... FAILED
thread 'main' panicked at risc0/r0vm/src/lib.rs:176:18:
called `Result::unwrap()` on an `Err` value: incompatible client version: 0.21.0-alpha.1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test::basic ... FAILED

failures:

---- test::svc stdout ----
thread 'test::svc' panicked at smartcore-ml/src/main.rs:157:58:
called `Result::unwrap()` on an `Err` value: failed to fill whole buffer
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::basic stdout ----
thread 'test::basic' panicked at smartcore-ml/src/main.rs:69:54:
called `Result::unwrap()` on an `Err` value: failed to fill whole buffer


failures:
    test::basic
    test::svc

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

error: test failed, to rerun pass `--bin smartcore-ml````

**Comment by weikengchen** [comment]
You shall run the command at the root directory of this repository. So, in `risc0-main`, run 
```
cargo install --path risc0/cargo-risczero
```

**Comment by saileshp56** [comment]
> The issue is about incompatible client version: 0.21.0-alpha.1. Basically, the `host` calls `r0vm` to generate the proof, but `r0vm` (which is from the previous installation, and would be older) finds that the version mismatches, and refuses to proceed.
> 
> Here is the solution:
> 
> * git clone this repo, which I think you have already done.
> * `cargo install --path risc0/cargo-risczero` which would update the system's `cargo-risczero` and `r0vm` to 0.21.0-alpha.1.

Is there a way to simply downgrade them all to 0.19? I have heard it is a stable version
