### ISSUE TITLE
[BUG] `examples/digital-signature` fails with `--features=risc0-zkvm/metal`

### ISSUE THREAD

**Issue by matthiasgeihs** [risc0/risc0#1392]
## Bug Report

When running the `digital-signature` example with feature `risc0-zkvm/metal`, it fails with
```
Running `/risc0/examples/target/release/digital-signature 'This is a signed message' --passphrase=passw0rd`
thread 'main' panicked at /risc0/risc0/zkvm/src/host/recursion/prove/exec.rs:158:17:
index out of bounds: the len is 1179 but the index is 2281702539
...
  20: digital_signature::sign
             at ./src/lib.rs:57:19
  21: digital_signature::main
             at ./src/main.rs:37:27
...
```
https://github.com/risc0/risc0/blob/83cf6867025846cd8ec91d9776ef8fb6c74b3b88/examples/digital-signature/src/lib.rs#L57

## Steps to Reproduce
1. Clone `risc0` at 83cf6867025846cd8ec91d9776ef8fb6c74b3b88 and perform setup procedure.
2. Go to `examples/digital-signature`.
3. Run `cargo run --release --features=risc0-zkvm/metal -- "This is a signed message" --passphrase="passw0rd`.

## Expected behavior

Should succeed.

Observations:
- Runs fine without `metal` feature.
- Test runs fine with `metal` feature.

## Your Environment
- risc0-zkvm version: 83cf6867025846cd8ec91d9776ef8fb6c74b3b88
- Rust version: 1.73.0
- Platform/OS: macOS 14.2.1, M1 Pro

**Comment by SchmErik** [comment]
I'm on 859b11867cffe3a985841a23d0b9b1c6395ec6b9 and I'm unable to reproduce this. I'm using 14.3.1 M1
```
% cargo run --release -F metal -- "This is a signed message" --passphrase="passw0rd"

....

     Running `/Users/erik/risc0/examples/target/release/digital-signature 'This is a signed message' --passphrase=passw0rd`
Inputs
        message: "This is a signed message"
Commitment:
        message: Digest(55256ea6467b849cd2985241d6333e6d14c6e1198903ee5d690b24b1084d0fe3)
        identity: Digest(2f9095c070680fc3435f4a68d21cdb05feb0ec1c20edad1ef6dcd9c1541b2904)
Integrity Checks:
        message: valid
        receipt: valid
```

Here's release-0.21 branch on 4afa9d39b2d8e37e2bee9173552efc1653e101e4:
```
% cargo run --release -F metal -- "This is a signed message" --passphrase="passw0rd"

...

     Running `/Users/erik/risc0/examples/target/release/digital-signature 'This is a signed message' --passphrase=passw0rd`
Inputs
        message: "This is a signed message"
Commitment:
        message: Digest(55256ea6467b849cd2985241d6333e6d14c6e1198903ee5d690b24b1084d0fe3)
        identity: Digest(2f9095c070680fc3435f4a68d21cdb05feb0ec1c20edad1ef6dcd9c1541b2904)
Integrity Checks:
        message: valid
        receipt: valid
```

**Comment by matthiasgeihs** [comment]
Can confirm that it now works for me on e37f5be4e95ca05c85e3c32f5c5a50943ac0abb5.
