### ISSUE TITLE
[Bug] addition overflow panic while reading a RISC Zero Program

### ISSUE THREAD

**Issue by pventuzelo** [risc0/risc0#529]
# addition overflow panic while reading a RISC Zero Program

We (@fuzzinglabs & @lambdaclass) found an addition overflow issue in risc0 while reading a RISC Zero Program.

## Expected Behavior

It should not crash.

## Your Environment

-  87adc831b195cd52aac7c49bf9894568baa7d372
-  cargo 1.70.0-nightly (15d090969 2023-03-21)
-  Ubuntu 20.04

## Steps to reproduce

Download: 

Testing program:
``` rust
use risc0_zkvm::{Program, MEM_SIZE};

fn add_overflow_risc0_program() {
    let data = b"\x7f\x45\x4c\x46\x01\x01\x01\x04\x00\x00\x00\x00\x00\x04\x04\x00\x02\x00\xf3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\xf3\x10\x00\x02\x00\x00\x20\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x01\x00\x01\x02\x7f\x01\x04\x00\x00\x00\x00\x00\x01\x7f\xff\xff\xff\x00\x00\x00\x00\x7f\x00\x00\x00\x00\x00\x00\x00\x00\x7f\x45\x4c\x46\x04\x04\x00\x00\xc0\x00\x04\x9e\x53\xff\xff\xc1\x46\x4c\x45\x04\x00\xf3\xe9\x00\x00\x00\x00\x00\x37\x04\x00\xfb\x00\xff\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x7f\x02\x01\x00\x01\x01\x00\x00\x00\x02\x00\x00\x00\x01\xbb\xfd\xff\x00\x08\x9c\x07\x00\x00\x00\x00\x02\x02\xff\x01\x01\x0b\x00\x00\x00\x00\x00\x00\xff\xc7\xc7\xc7\xc7\x52\x99\x41\x34\x00\x00\x00\x0c\xbe\x10\x13\x14\x1b\x55\xe8\x7b\x6f\xaf\x9b\xb5\x73\x1d\x5d\x43\xca\x5e\xbd\xdf\xc7\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x06\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfb\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\xf3\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\xff\x02\x00\xff\x00\x00\x00\x00\x04\x04\x00\x00\x00\xec\xec\xec\xec\xec\x00\x00\x05\x00\x00\x00\x00\x04\x00\x04\x00\x00\x00\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x02\x00\xff\x00\x00\x00\x00\xe0\x89\x0b\x00\x00\x00\x00\x00\x00\x00\x05\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x04\x01\x00\x00\x00\x00\x00\x7f\x00\x07\x04\x00\x00\x33\x36\xbd\x00\x00\x00\x06\x06\x06\x06\x06\x06\x06\x06\x06\x06\x06\x06\x06\x06\x06\x46\x4c\x45\x7f\x5f\x45\x7f\x28\xa3\x5d\xaf\xe9\xbf\x00\x00\x04\x00\x00\x00\x02\x00\x02\x00\x00\x00\x05\x00\x00\x00\x00\xf1\x00\x01\x01\x01\x04\x37\x00\x00\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x01\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x46\x4c\x45\xff\xff\xff\x00\x4d\x4d\x46\x00\x00\x04\x00\x7f\x00\x00\x00\x04\x00\x02\x00\x00\xf3\x01\x00\x05\x00\x4c\x46\x00\x4c\x3a\xb3\x4d\xaf";
    let _ = Program::load_elf(&data, MEM_SIZE as u32);
}

```

## Root cause

```
thread 'main' panicked at 'attempt to add with overflow', /home/scop/Documents/risc0/risc0/risc0/zkvm/src/binfmt/elf.rs:57:28
```

Related code: https://github.com/risc0/risc0/blob/0b7a20347498624393946e52028e8f0388d5c16d/risc0/zkvm/src/binfmt/elf.rs#L57

## Detailed behavior
``` sh
thread 'main' panicked at 'attempt to add with overflow', /home/scop/Documents/risc0/risc0/risc0/zkvm/src/binfmt/elf.rs:57:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/panicking.rs:114:5
   3: risc0_zkvm::binfmt::elf::Program::load_elf
             at /home/scop/Documents/risc0/risc0/risc0/zkvm/src/binfmt/elf.rs:57:28
   4: risc0_fuzzing::add_overflow_risc0_program
             at ./src/main.rs:32:13
   5: risc0_fuzzing::main
             at ./src/main.rs:9:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/a266f11990d9544ee408e213e1eec8cc9eb032b7/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by pventuzelo** [comment]
Fixed in: https://github.com/risc0/risc0/commit/bdb811ab9a3f43f7cb589bfeb25df9aebef95f6f
