### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by nihaoqingtuan** [risc0/risc0#882]
when i run "cargo run -r -F cuda --example loop"
log:
```
   **Finished release [optimized + debuginfo] target(s) in 6m 00s
     Running `target/release/examples/loop`
|     Cycles |   Duration |        RAM |       Seal |      Speed |
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnknownError', /home/daibin/db/risc0/risc0/zkp/src/hal/cuda.rs:347:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'assertion failed: ok', risc0/zkvm/examples/loop.rs:126:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace**
```

**Comment by nihaoqingtuan** [comment]
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by nihaoqingtuan** [comment]
22.04.1-Ubuntu

**Comment by flaub** [comment]
What does `nvidia-smi` say?

**Comment by nihaoqingtuan** [comment]
> @nihaoqingtuan What does `nvidia-smi` say?

i update cuda version. it works

**Comment by Vap0RSh4wN** [comment]
> > @nihaoqingtuan What does `nvidia-smi` say?
> 
> i update cuda version. it works

hi may I ask you that which version of cuda you updated to solve this problem? thanks so much!
