### ISSUE TITLE
Error enabling `metal` on M1 Max: "Compute function exceeds available temporary registers"

### ISSUE THREAD

**Issue by malturki** [risc0/risc0#937]
Following the [Tutorial: Building your first zkVM application](https://github.com/risc0/risc0/blob/main/examples/hello-world/tutorial.md), I can compile and successfully generate the receipt. But when attempting to enable `metal` by requesting this feature in the host's configuration in `host/Cargo.toml`:
```
[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
hello-world-methods = { path = "../methods" }
risc0-zkvm = { version = "0.18.0" , features = [ "metal" ] }
serde = "1.0"
```

it compiles successfully, but fails at runtime with the following error:
```
     Running `target/release/host`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Compute function exceeds available temporary registers"', /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkp-0.18.0/src/hal/metal.rs:371:14
```

The full output with a minimal stack trace:
```
% RUST_BACKTRACE=1 cargo run --release
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
   Compiling libc v0.2.148
   Compiling proc-macro2 v1.0.67
   Compiling unicode-ident v1.0.12
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling serde v1.0.188
   Compiling rustix v0.38.15
   Compiling bitflags v2.4.0
   Compiling fastrand v2.0.1
   Compiling version_check v0.9.4
   Compiling typenum v1.17.0
   Compiling subtle v2.5.0
   Compiling once_cell v1.18.0
   Compiling const-oid v0.9.5
   Compiling option-ext v0.2.0
   Compiling pin-project-lite v0.2.13
   Compiling either v1.9.0
   Compiling core-foundation-sys v0.8.4
   Compiling glob v0.3.1
   Compiling memchr v2.6.4
   Compiling hex v0.4.3
   Compiling bitflags v1.3.2
   Compiling anyhow v1.0.75
   Compiling tracing-core v0.1.31
   Compiling generic-array v0.14.7
   Compiling num-traits v0.2.16
   Compiling quote v1.0.33
   Compiling num-integer v0.1.45
   Compiling syn v2.0.37
   Compiling memoffset v0.9.0
   Compiling crossbeam-utils v0.8.16
   Compiling itoa v1.0.9
   Compiling jobserver v0.1.26
   Compiling errno v0.3.4
   Compiling cc v1.0.83
   Compiling dirs-sys v0.4.1
   Compiling cpufeatures v0.2.9
   Compiling directories v5.0.1
   Compiling core-foundation v0.9.3
   Compiling getrandom v0.2.10
   Compiling rand_core v0.6.4
   Compiling tempfile v3.8.0
   Compiling crossbeam-epoch v0.9.15
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling digest v0.10.7
   Compiling log v0.4.20
   Compiling sha2 v0.10.8
   Compiling syn v1.0.109
   Compiling risc0-build-kernel v0.18.0
   Compiling num-bigint v0.3.3
   Compiling lazy_static v1.4.0
   Compiling scopeguard v1.2.0
   Compiling thiserror v1.0.49
   Compiling radium v0.7.0
   Compiling byteorder v1.4.3
   Compiling paste v1.0.14
   Compiling rayon-core v1.12.0
   Compiling crossbeam-deque v0.8.3
   Compiling matrixmultiply v0.3.8
   Compiling futures-core v0.3.28
   Compiling tap v1.0.1
   Compiling wyz v0.5.1
   Compiling malloc_buf v0.0.6
   Compiling foreign-types-shared v0.3.1
   Compiling ppv-lite86 v0.2.17
   Compiling ryu v1.0.15
   Compiling rawpointer v0.2.1
   Compiling funty v2.0.0
   Compiling serde_json v1.0.107
   Compiling rayon v1.8.0
   Compiling addchain v0.2.0
   Compiling bitvec v1.0.1
   Compiling rand_chacha v0.3.1
   Compiling num-complex v0.4.4
   Compiling core-graphics-types v0.1.2
   Compiling mio v0.8.8
   Compiling socket2 v0.5.4
   Compiling num_cpus v1.16.0
   Compiling slab v0.4.9
   Compiling futures-task v0.3.28
   Compiling block v0.1.6
   Compiling risc0-zkp v0.18.0
   Compiling ndarray v0.15.6
   Compiling rand v0.8.5
   Compiling blake2 v0.10.6
   Compiling indexmap v1.9.3
   Compiling aho-corasick v1.1.1
   Compiling futures-util v0.3.28
   Compiling risc0-zkvm-platform v0.18.0
   Compiling risc0-sys v0.18.0
   Compiling objc_exception v0.1.2
   Compiling regex-syntax v0.7.5
   Compiling fnv v1.0.7
   Compiling security-framework-sys v2.9.1
   Compiling itertools v0.11.0
   Compiling pin-utils v0.1.0
   Compiling native-tls v0.2.11
   Compiling httparse v1.8.0
   Compiling semver v1.0.19
   Compiling tinyvec_macros v0.1.1
   Compiling camino v1.1.6
   Compiling futures-io v0.3.28
   Compiling futures-channel v0.3.28
   Compiling objc v0.2.7
   Compiling hashbrown v0.12.3
   Compiling regex-automata v0.3.9
   Compiling futures-sink v0.3.28
   Compiling tinyvec v1.6.0
   Compiling security-framework v2.9.2
   Compiling autotools v0.2.6
   Compiling hashbrown v0.14.1
   Compiling regex v1.9.6
   Compiling try-lock v0.2.4
   Compiling prettyplease v0.2.15
   Compiling equivalent v1.0.1
   Compiling percent-encoding v2.3.0
   Compiling crc32fast v1.3.2
   Compiling elf v0.7.2
   Compiling form_urlencoded v1.2.0
   Compiling indexmap v2.0.2
   Compiling want v0.3.1
   Compiling protobuf-src v1.1.0+21.5
   Compiling unicode-normalization v0.1.22
   Compiling risc0-circuit-rv32im-sys v0.18.0
   Compiling socket2 v0.4.9
   Compiling home v0.5.5
   Compiling unicode-bidi v0.3.13
   Compiling fixedbitset v0.4.2
   Compiling httpdate v1.0.3
   Compiling static_assertions v1.1.0
   Compiling adler v1.0.2
   Compiling tower-service v0.3.2
   Compiling twox-hash v1.6.3
   Compiling miniz_oxide v0.7.1
   Compiling idna v0.4.0
   Compiling petgraph v0.6.4
   Compiling which v4.4.2
   Compiling cpp_demangle v0.4.3
   Compiling multimap v0.8.3
   Compiling heck v0.4.1
   Compiling flate2 v1.0.27
   Compiling url v2.4.1
   Compiling encoding_rs v0.8.33
   Compiling mime v0.3.17
   Compiling base64 v0.21.4
   Compiling stable_deref_trait v1.2.0
   Compiling fallible-iterator v0.2.0
   Compiling libm v0.2.7
   Compiling ipnet v2.8.0
   Compiling risc0-circuit-rv32im v0.18.0
   Compiling gimli v0.27.3
   Compiling memmap2 v0.5.10
   Compiling smallvec v1.11.1
   Compiling rustc-demangle v0.1.23
   Compiling inventory v0.3.12
   Compiling downcast-rs v1.2.0
   Compiling rrs-lib v0.1.0
   Compiling crypto-bigint v0.5.3
   Compiling serde_derive v1.0.188
   Compiling tracing-attributes v0.1.26
   Compiling bytemuck_derive v1.5.0
   Compiling thiserror-impl v1.0.49
   Compiling foreign-types-macros v0.2.3
   Compiling prost-derive v0.12.1
   Compiling ff_derive v0.13.0
   Compiling foreign-types v0.5.0
   Compiling metal v0.25.0
   Compiling ff v0.13.0
   Compiling lazy-regex-proc_macros v2.4.1
   Compiling ruzstd v0.3.1
   Compiling bytemuck v1.14.0
   Compiling risc0-core v0.18.0
   Compiling object v0.31.1
   Compiling typetag-impl v0.2.13
   Compiling lazy-regex v2.5.0
   Compiling num-derive v0.4.0
   Compiling tracing v0.1.37
   Compiling addr2line v0.20.0
   Compiling bytes v1.5.0
   Compiling tokio v1.32.0
   Compiling http v0.2.9
   Compiling tokio-util v0.7.9
   Compiling http-body v0.4.5
   Compiling risc0-binfmt v0.18.0
   Compiling prost v0.12.1
   Compiling h2 v0.3.21
   Compiling cargo-platform v0.1.3
   Compiling prost-types v0.12.1
   Compiling cargo_metadata v0.17.0
   Compiling tokio-native-tls v0.3.1
   Compiling serde_urlencoded v0.7.1
   Compiling prost-build v0.12.1
   Compiling hyper v0.14.27
   Compiling risc0-build v0.18.0
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.20
   Compiling erased-serde v0.3.31
   Compiling typetag v0.2.13
   Compiling bonsai-sdk v0.4.0
   Compiling bincode v1.3.3
   Compiling hello-world-methods v0.1.0 (/Users/musab/GitHub/experiment/checker/methods)
multiply: Starting build for riscv32im-risc0-zkvm-elftobuf-src(build), reqwest, hello-world-methods(build), ri...
multiply:    Compiling proc-macro2 v1.0.67
multiply:    Compiling unicode-ident v1.0.12
multiply:    Compiling typenum v1.17.0
multiply:    Compiling version_check v0.9.4
multiply:    Compiling serde v1.0.188
multiply:    Compiling paste v1.0.14
multiply:    Compiling const-oid v0.9.5
multiply:    Compiling cfg-if v1.0.0
multiply:    Compiling anyhow v1.0.75
multiply:    Compiling subtle v2.5.0
multiply:    Compiling libm v0.2.7
multiply:    Compiling rand_core v0.6.4
multiply:    Compiling tracing-core v0.1.31
multiply:    Compiling pin-project-lite v0.2.13
multiply:    Compiling risc0-zkp v0.18.0
multiply:    Compiling hex v0.4.3
multiply:    Compiling generic-array v0.14.7
multiply:    Compiling risc0-zkvm-platform v0.18.0
multiply:    Compiling risc0-zkvm v0.18.0
multiply:    Compiling getrandom v0.2.10
multiply:    Compiling quote v1.0.33
multiply:    Compiling syn v2.0.37
multiply:    Compiling block-buffer v0.10.46/288: protobuf-src(build), hello-world-methods(build), risc0-circu...
multiply:    Compiling crypto-common v0.1.6
multiply:    Compiling digest v0.10.7
multiply:    Compiling blake2 v0.10.6
multiply:    Compiling bytemuck_derive v1.5.0
multiply:    Compiling serde_derive v1.0.188
multiply:    Compiling tracing-attributes v0.1.26
multiply:    Compiling bytemuck v1.14.0
multiply:    Compiling tracing v0.1.37
multiply:    Compiling risc0-core v0.18.0
multiply:    Compiling multiply v0.1.0 (/Users/musab/GitHub/experiment/checker/methods/guest)
multiply:     Finished release [optimized] target(s) in 7.22s
   Compiling risc0-zkvm v0.18.0
   Compiling host v0.1.0 (/Users/musab/GitHub/experiment/checker/host)
    Finished release [optimized + debuginfo] target(s) in 8m 07s
     Running `target/release/host`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Compute function exceeds available temporary registers"', /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkp-0.18.0/src/hal/metal.rs:371:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1076:23
   4: risc0_zkp::hal::metal::MetalHal<MH>::dispatch
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkp-0.18.0/src/hal/metal.rs:368:30
   5: <risc0_circuit_rv32im::metal::MetalCircuitHal<MH> as risc0_zkp::hal::CircuitHal<risc0_zkp::hal::metal::MetalHal<MH>>>::eval_check
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-circuit-rv32im-0.18.0/src/metal.rs:89:9
   6: risc0_zkp::prove::prover::Prover<H>::finalize
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkp-0.18.0/src/prove/prover.rs:128:9
   7: <risc0_zkvm::host::server::prove::prover_impl::ProverImpl<H,C> as risc0_zkvm::host::server::prove::ProverServer>::prove_segment
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.18.0/src/host/server/prove/prover_impl.rs:130:20
   8: <risc0_zkvm::host::server::prove::prover_impl::ProverImpl<H,C> as risc0_zkvm::host::server::prove::ProverServer>::prove_session
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.18.0/src/host/server/prove/prover_impl.rs:71:27
   9: risc0_zkvm::host::server::prove::ProverServer::prove
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.18.0/src/host/server/prove/mod.rs:60:9
  10: <risc0_zkvm::host::client::prove::local::LocalProver as risc0_zkvm::host::client::prove::Prover>::prove
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.18.0/src/host/client/prove/local.rs:44:9
  11: risc0_zkvm::host::client::prove::Prover::prove_elf_with_ctx
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.18.0/src/host/client/prove/mod.rs:109:9
  12: risc0_zkvm::host::client::prove::Prover::prove_elf
             at /Users/musab/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.18.0/src/host/client/prove/mod.rs:91:9
  13: host::main
             at ./host/src/main.rs:27:19
  14: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This is running on an M1 Max MacBook Pro with 64GB of RAM, and macOS 13.5.2:

```
Graphics/Displays:

    Apple M1 Max:

      Chipset Model: Apple M1 Max
      Type: GPU
      Bus: Built-In
      Total Number of Cores: 32
      Vendor: Apple (0x106b)
      Metal Support: Metal 3

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,2
      Model Number: Z14X000GDLL/A
      Chip: Apple M1 Max
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 64 GB
      System Firmware Version: 10151.1.1
      OS Loader Version: 10151.1.1
```

This is using the stable arm64 version (1.72.1) of the Rust toolchain. `rust-toolchain.toml` in the root of this tutorial project is as follows:
```
[toolchain]
channel = "stable-aarch64-apple-darwin"
components = ["rustfmt", "rust-src"]
profile = "minimal"
```

**Comment by SchmErik** [comment]
Hi @malturki, I hope you've been well! Thanks for finding this issue.

Notes: after trying a few things, I see that this also happening on a few examples hello-world and json in the risc0/examples directory. My setup is the same except i'm running macOS 14.0

**Comment by SchmErik** [comment]
More notes: this does not occur on M2 macs

**Comment by malturki** [comment]
Hey @SchmErik, it's great to connect with you again. And thanks for confirming this issue. I wonder if it has to do with recent versions of macOS.

**Comment by malturki** [comment]
> More notes: this does not occur on M2 macs

I just tried the tutorial as above on an M2 Pro and was able to reproduce the same error when `metal` is enabled. This was on macOS 14.0. This is the relevant system information:

```
Graphics/Displays:

    Apple M2 Pro:

      Chipset Model: Apple M2 Pro
      Type: GPU
      Bus: Built-In
      Total Number of Cores: 16
      Vendor: Apple (0x106b)
      Metal Support: Metal 3

Hardware:

    Hardware Overview:

      Model Name: Mac mini
      Model Identifier: Mac14,12
      Model Number: Z170000FTLL/A
      Chip: Apple M2 Pro
      Total Number of Cores: 10 (6 performance and 4 efficiency)
      Memory: 32 GB
      System Firmware Version: 10151.1.1
      OS Loader Version: 10151.1.1
```

I'm wondering if M2 Max (and higher) are the only models unaffected by this.

**Comment by blmalone** [comment]
+1 on seeing this issue. 

```
Software:

    System Software Overview:

      System Version: macOS 14.0 (23A344)
      Kernel Version: Darwin 23.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Blaine’s MacBook Pro
      User Name: Blaine Malone (blainemalone)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 17 hours, 59 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,1
      Model Number: Z14W00105LL/A
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 10151.1.1
      OS Loader Version: 10151.1.1
      Serial Number (system): V1Q0F3HNXY
      Hardware UUID: 7710ABB4-8136-5DD0-964A-373EB5422871
      Provisioning UDID: 00006000-0016083A34A1801E
      Activation Lock Status: Disabled

Graphics/Displays:

    Apple M1 Pro:

      Chipset Model: Apple M1 Pro
      Type: GPU
      Bus: Built-In
      Total Number of Cores: 16
      Vendor: Apple (0x106b)
      Metal Support: Metal 3
      Displays:
        Color LCD:
          Display Type: Built-in Liquid Retina XDR Display
          Resolution: 3456 x 2234 Retina
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Automatically Adjust Brightness: Yes
          Connection Type: Internal
```

**Comment by flaub** [comment]
We probably need to look into pre-compiling the JIT portion: https://developer.apple.com/videos/play/wwdc2022/10102/

**Comment by flaub** [comment]
Closing in favor of #999
