### ISSUE TITLE
xtask appears broken for `browser-verify`; can't execute example

### ISSUE THREAD

**Issue by jakehemmerle** [risc0/risc0#985]
## `xtask` broken

I'm trying to verify an image id and receipt pair in a freestanding `wasm32-unknown-unknown` environment (ie no browser APIs, no WASI). I've been looking at the `browser-verify` example for most of this, but having some issues getting that to actually run.

In the example's README.md, the quickstart instructions are as follows:
```
cargo xtask install
cargo xtask gen-receipt
```

Both fail with 
```
~/codebases/risc0/examples/browser-verify main ❯ cargo xtask install
error: package(s) `xtask` not found in workspace `/Users/jake/codebases/risc0/examples`
~/codebases/risc0/examples/browser-verify main ❯ cargo xtask gen-receipt
error: package(s) `xtask` not found in workspace `/Users/jake/codebases/risc0/examples`
```

I tried installing https://github.com/matklad/cargo-xtask with no luck, and I also tried manually running the aliases in the `.cargo/config.toml` file like `cargo run --package xtask --release -- install`, with no luck.

---

## `browser-verify` testing broken

If `xtask` is legacy at this point, I'm still when trying to run it as follows:

```bash
~/codebases/risc0/examples/browser-verify main ❯ npm test -- --safari

> browser-verify@0.1.0 test
> cargo test && wasm-pack test --headless --safari

warning: patch for `smartcore` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
   Compiling log v0.4.20
   Compiling risc0-zkvm-receipts v0.19.0-alpha.1 (/Users/jake/codebases/risc0/risc0/zkvm/receipts)
   Compiling wasm-bindgen-backend v0.2.87
   Compiling risc0-zkp v0.19.0-alpha.1 (/Users/jake/codebases/risc0/risc0/zkp)
   Compiling risc0-binfmt v0.19.0-alpha.1 (/Users/jake/codebases/risc0/risc0/binfmt)
   Compiling risc0-circuit-rv32im v0.19.0-alpha.1 (/Users/jake/codebases/risc0/risc0/circuit/rv32im)
   Compiling risc0-zkvm v0.19.0-alpha.1 (/Users/jake/codebases/risc0/risc0/zkvm)
   Compiling wasm-bindgen-macro-support v0.2.87
   Compiling wasm-bindgen-macro v0.2.87
   Compiling wasm-bindgen v0.2.87
   Compiling js-sys v0.3.64
   Compiling console_error_panic_hook v0.1.7
   Compiling wasm-bindgen-futures v0.4.37
   Compiling wasm-bindgen-test v0.3.37
   Compiling browser-verify v0.1.0 (/Users/jake/codebases/risc0/examples/browser-verify)
    Finished test [optimized + debuginfo] target(s) in 5.68s
     Running unittests src/lib.rs (/Users/jake/codebases/risc0/examples/target/debug/deps/browser_verify-b424f8f985211b16)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/app.rs (/Users/jake/codebases/risc0/examples/target/debug/deps/app-d8cd02bcbef3a115)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

[INFO]: 🎯  Checking for the Wasm target...
warning: patch for `smartcore` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
   Compiling log v0.4.20
   Compiling risc0-zkvm-receipts v0.19.0-alpha.1 (/Users/jake/codebases/risc0/risc0/zkvm/receipts)
   Compiling wasm-bindgen-backend v0.2.87
   Compiling wasm-bindgen-macro-support v0.2.87
   Compiling wasm-bindgen-macro v0.2.87
   Compiling wasm-bindgen v0.2.87
   Compiling js-sys v0.3.64
   Compiling console_error_panic_hook v0.1.7
   Compiling wasm-bindgen-futures v0.4.37
   Compiling wasm-bindgen-test v0.3.37
   Compiling browser-verify v0.1.0 (/Users/jake/codebases/risc0/examples/browser-verify)
    Finished dev [optimized + debuginfo] target(s) in 7.71s
[INFO]: ⬇️  Installing wasm-bindgen...
warning: patch for `smartcore` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
   Compiling risc0-zkvm-receipts v0.19.0-alpha.1 (/Users/jake/codebases/risc0/risc0/zkvm/receipts)
   Compiling browser-verify v0.1.0 (/Users/jake/codebases/risc0/examples/browser-verify)
    Finished test [optimized + debuginfo] target(s) in 0.41s
     Running unittests src/lib.rs (/Users/jake/codebases/risc0/examples/target/wasm32-unknown-unknown/debug/deps/browser_verify-ec8020e95928baca.wasm)
no tests to run!
     Running tests/app.rs (/Users/jake/codebases/risc0/examples/target/wasm32-unknown-unknown/debug/deps/app-6d8aa8efa02fc8c1.wasm)
Set timeout to 20 seconds...
Running headless tests in Safari on `http://127.0.0.1:63947/`
Try find `webdriver.json` for configure browser's capabilities:
Not found
running 1 test                                    

test app::test_verify ... FAIL

failures:

---- app::test_verify output ----
    error output:
        panicked at browser-verify/tests/app.rs:24:62:
        called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))
        
        Stack:
        
        @http://127.0.0.1:63946/wasm-bindgen-test:507:30
        logError@http://127.0.0.1:63946/wasm-bindgen-test:155:23
        wasm-stub@[wasm code]
        <?>.wasm-function[console_error_panic_hook::hook::h41ac3c5da157acdd]@[wasm code]
        <?>.wasm-function[wasm_bindgen_test::__rt::Context::new::{{closure}}::{{closure}}::h1c7b705b144b7bb2]@[wasm code]
        <?>.wasm-function[std::panicking::rust_panic_with_hook::h3aa054d35a0817d7]@[wasm code]
        <?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h2f73e4cf6cd6319a]@[wasm code]
        <?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h98ac61a6abbff7e9]@[wasm code]
        <?>.wasm-function[rust_begin_unwind]@[wasm code]
        <?>.wasm-function[core::panicking::panic_fmt::h3e1dd3d08288569e]@[wasm code]
        <?>.wasm-function[core::result::unwrap_failed::h8b3db0f11171b57b]@[wasm code]
        <?>.wasm-function[app::test_verify::h8d59dc18075d90dd]@[wasm code]
        <?>.wasm-function[<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::{{closure}}::{{closure}}::h9dd96672ce3578d4]@[wasm code]
        <?>.wasm-function[wasm_bindgen::convert::closures::invoke0_mut::h8349c23053174761]@[wasm code]
        wasm-stub@[wasm code]
        __wbg_adapter_31@http://127.0.0.1:63946/wasm-bindgen-test:272:73
        cb0@http://127.0.0.1:63946/wasm-bindgen-test:444:44
        @http://127.0.0.1:63946/:38:39
        @http://127.0.0.1:63946/wasm-bindgen-test:449:30
        handleError@http://127.0.0.1:63946/wasm-bindgen-test:277:23
        wasm-stub@[wasm code]
        <?>.wasm-function[wasm_bindgen_test::__rt::__wbg_test_invoke::h7e50854ea5fbd56f]@[wasm code]
        <?>.wasm-function[<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::hab3a649755635407]@[wasm code]
        <?>.wasm-function[<wasm_bindgen_test::__rt::ExecuteTests as core::future::future::Future>::poll::hec66c8b5d4c35d1a]@[wasm code]
        <?>.wasm-function[wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hee8296e6e2dc23ac]@[wasm code]
        <?>.wasm-function[wasm_bindgen_futures::task::singlethread::Task::run::h81be225c46ec7d77]@[wasm code]
        <?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::he7fff773e55dd8ab]@[wasm code]
        <?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h89a0a72a4cb49205]@[wasm code]
        wasm-stub@[wasm code]
        __wbg_adapter_18@http://127.0.0.1:63946/wasm-bindgen-test:175:134
        real@http://127.0.0.1:63946/wasm-bindgen-test:138:21
        
        
    
    JS exception that was thrown:
        RuntimeError: Unreachable code should not be executed (evaluating 'wasm.wasm_bindgen__convert__closures__invoke0_mut__h8349c23053174761(arg0, arg1)')
        <?>.wasm-function[__rust_start_panic]@[wasm code]
        <?>.wasm-function[rust_panic]@[wasm code]
        <?>.wasm-function[std::panicking::rust_panic_with_hook::h3aa054d35a0817d7]@[wasm code]
        <?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h2f73e4cf6cd6319a]@[wasm code]
        <?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h98ac61a6abbff7e9]@[wasm code]
        <?>.wasm-function[rust_begin_unwind]@[wasm code]
        <?>.wasm-function[core::panicking::panic_fmt::h3e1dd3d08288569e]@[wasm code]
        <?>.wasm-function[core::result::unwrap_failed::h8b3db0f11171b57b]@[wasm code]
        <?>.wasm-function[app::test_verify::h8d59dc18075d90dd]@[wasm code]
        <?>.wasm-function[<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::{{closure}}::{{closure}}::h9dd96672ce3578d4]@[wasm code]
        <?>.wasm-function[wasm_bindgen::convert::closures::invoke0_mut::h8349c23053174761]@[wasm code]
        wasm-stub@[wasm code]
        __wbg_adapter_31@http://127.0.0.1:63946/wasm-bindgen-test:272:73
        cb0@http://127.0.0.1:63946/wasm-bindgen-test:444:44
        @http://127.0.0.1:63946/:38:39
        @http://127.0.0.1:63946/wasm-bindgen-test:449:30
        handleError@http://127.0.0.1:63946/wasm-bindgen-test:277:23
        wasm-stub@[wasm code]
        <?>.wasm-function[wasm_bindgen_test::__rt::__wbg_test_invoke::h7e50854ea5fbd56f]@[wasm code]
        <?>.wasm-function[<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::hab3a649755635407]@[wasm code]
        <?>.wasm-function[<wasm_bindgen_test::__rt::ExecuteTests as core::future::future::Future>::poll::hec66c8b5d4c35d1a]@[wasm code]
        <?>.wasm-function[wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hee8296e6e2dc23ac]@[wasm code]
        <?>.wasm-function[wasm_bindgen_futures::task::singlethread::Task::run::h81be225c46ec7d77]@[wasm code]
        <?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::he7fff773e55dd8ab]@[wasm code]
        <?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h89a0a72a4cb49205]@[wasm code]
        wasm-stub@[wasm code]
        __wbg_adapter_18@http://127.0.0.1:63946/wasm-bindgen-test:175:134
        real@http://127.0.0.1:63946/wasm-bindgen-test:138:21

failures:

    app::test_verify

test result: FAILED. 0 passed; 1 failed; 0 ignored


console.log div contained:
    panicked at browser-verify/tests/app.rs:24:62:
    called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))
    
    Stack:
    
    @http://127.0.0.1:63946/wasm-bindgen-test:507:30
    logError@http://127.0.0.1:63946/wasm-bindgen-test:155:23
    wasm-stub@[wasm code]
    <?>.wasm-function[console_error_panic_hook::hook::h41ac3c5da157acdd]@[wasm code]
    <?>.wasm-function[wasm_bindgen_test::__rt::Context::new::{{closure}}::{{closure}}::h1c7b705b144b7bb2]@[wasm code]
    <?>.wasm-function[std::panicking::rust_panic_with_hook::h3aa054d35a0817d7]@[wasm code]
    <?>.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h2f73e4cf6cd6319a]@[wasm code]
    <?>.wasm-function[std::sys_common::backtrace::__rust_end_short_backtrace::h98ac61a6abbff7e9]@[wasm code]
    <?>.wasm-function[rust_begin_unwind]@[wasm code]
    <?>.wasm-function[core::panicking::panic_fmt::h3e1dd3d08288569e]@[wasm code]
    <?>.wasm-function[core::result::unwrap_failed::h8b3db0f11171b57b]@[wasm code]
    <?>.wasm-function[app::test_verify::h8d59dc18075d90dd]@[wasm code]
    <?>.wasm-function[<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::{{closure}}::{{closure}}::h9dd96672ce3578d4]@[wasm code]
    <?>.wasm-function[wasm_bindgen::convert::closures::invoke0_mut::h8349c23053174761]@[wasm code]
    wasm-stub@[wasm code]
    __wbg_adapter_31@http://127.0.0.1:63946/wasm-bindgen-test:272:73
    cb0@http://127.0.0.1:63946/wasm-bindgen-test:444:44
    @http://127.0.0.1:63946/:38:39
    @http://127.0.0.1:63946/wasm-bindgen-test:449:30
    handleError@http://127.0.0.1:63946/wasm-bindgen-test:277:23
    wasm-stub@[wasm code]
    <?>.wasm-function[wasm_bindgen_test::__rt::__wbg_test_invoke::h7e50854ea5fbd56f]@[wasm code]
    <?>.wasm-function[<wasm_bindgen_test::__rt::TestFuture<F> as core::future::future::Future>::poll::hab3a649755635407]@[wasm code]
    <?>.wasm-function[<wasm_bindgen_test::__rt::ExecuteTests as core::future::future::Future>::poll::hec66c8b5d4c35d1a]@[wasm code]
    <?>.wasm-function[wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hee8296e6e2dc23ac]@[wasm code]
    <?>.wasm-function[wasm_bindgen_futures::task::singlethread::Task::run::h81be225c46ec7d77]@[wasm code]
    <?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::he7fff773e55dd8ab]@[wasm code]
    <?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h89a0a72a4cb49205]@[wasm code]
    wasm-stub@[wasm code]
    __wbg_adapter_18@http://127.0.0.1:63946/wasm-bindgen-test:175:134
    real@http://127.0.0.1:63946/wasm-bindgen-test:138:21
    
    

Error: some tests failed                          
error: test failed, to rerun pass `--test app`

Caused by:
  process didn't exit successfully: `/Users/jake/Library/Caches/.wasm-pack/wasm-bindgen-cargo-install-0.2.87/wasm-bindgen-test-runner /Users/jake/codebases/risc0/examples/target/wasm32-unknown-unknown/debug/deps/app-6d8aa8efa02fc8c1.wasm` (exit status: 1)
note: test exited abnormally; to see the full output pass --nocapture to the harness.
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit status: 1
  full command: cd "/Users/jake/codebases/risc0/examples/browser-verify" && CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER="/Users/jake/Library/Caches/.wasm-pack/wasm-bindgen-cargo-install-0.2.87/wasm-bindgen-test-runner" SAFARIDRIVER="/System/Cryptexes/App/usr/bin/safaridriver" WASM_BINDGEN_TEST_ONLY_WEB="1" "cargo" "test" "--target" "wasm32-unknown-unknown"
  ```

I'm using the latest lts/hydrogen for node. I also enabled "Allow Remote Automation" in Safari as well, but did not test other browsers.

Any suggestions?

**Comment by flaub** [comment]
I looks like you're trying to run `cargo xtask` from the `examples` workspace. It needs to be run from the root of the project.

**Comment by jakehemmerle** [comment]
That was it, thanks. I haven't used hierarchical workspaces before; now I know.

I was also able to get the verifier working in the freestanding Wasm environment.

Thanks!
